package context

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"bctx/internal/config"

	"gopkg.in/yaml.v3"
)

// resourceTypeDescriptions maps type to a human-readable description.
var resourceTypeDescriptions = map[string]string{
	"rules":   "Rules, coding standards, documentation",
	"skills":  "Reusable skill definitions",
	"agents":  "Agent configurations",
	"plugins": "Plugin definitions",
}

// indexEntry represents a single resource in index.yaml.
type indexEntry struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
	Scope       string `yaml:"scope"`
	Category    string `yaml:"category"`
	Path        string `yaml:"path"`
}

// indexFile represents the index.yaml structure.
type indexFile struct {
	Type      string       `yaml:"type"`
	Resources []indexEntry `yaml:"resources"`
}

// GenerateNavigator writes ~/.claude/bayctx/CLAUDE.md — the agent entry point.
func GenerateNavigator() error {
	bctxDir := config.BctxDir()
	navigatorPath := filepath.Join(bctxDir, "CLAUDE.md")

	var b strings.Builder
	b.WriteString("# Context Resources\n\n")
	b.WriteString("bctx manages context resources in `~/.claude/bayctx/`. Each directory has an `index.yaml`\n")
	b.WriteString("listing available items. Only read a resource when its description\n")
	b.WriteString("matches your current task.\n\n")
	b.WriteString("## Resource Directories\n\n")
	b.WriteString("| Directory | Type | Description |\n")
	b.WriteString("|-----------|------|-------------|\n")

	for _, t := range config.ResourceTypes {
		desc := resourceTypeDescriptions[t]
		b.WriteString(fmt.Sprintf("| `~/.claude/bayctx/%s/` | %s | %s |\n", t, t, desc))
	}

	b.WriteString("\nRead the `index.yaml` in a directory to see available resources.\n")
	b.WriteString("Manage with: `bctx files|add|rm|toggle`\n")

	b.WriteString("\n## Project Context\n\n")
	b.WriteString("Project-specific context lives in `~/.claude/bayctx/projects/<project-name>/`.\n\n")
	b.WriteString("Key file: `status.md` — current project state, milestones, what's shipped, known issues.\n")
	b.WriteString("Read `status.md` at the start of work. Update it when you complete significant changes.\n")
	b.WriteString("Updates section is **append-only with date headings** (`### YYYY-MM-DD — description`).\n\n")
	b.WriteString("Other useful files: `architecture.md`, `design.md`, conventions, etc.\n\n")
	b.WriteString("Session-level progress is ephemeral. Project-level progress goes to `status.md`.\n")

	return os.WriteFile(navigatorPath, []byte(b.String()), 0644)
}

// GenerateAllIndexes generates index.yaml for each resource type directory.
func GenerateAllIndexes() error {
	files, err := List()
	if err != nil {
		return fmt.Errorf("listing context files: %w", err)
	}

	grouped := make(map[string][]ContextFile)
	for _, f := range files {
		if !f.Enabled {
			continue
		}
		t := f.Type
		if t == "" {
			t = "rules"
		}
		grouped[t] = append(grouped[t], f)
	}

	bctxDir := config.BctxDir()
	for _, t := range config.ResourceTypes {
		idx := indexFile{
			Type:      t,
			Resources: []indexEntry{},
		}

		for _, f := range grouped[t] {
			idx.Resources = append(idx.Resources, indexEntry{
				Name:        f.Name,
				Description: f.Description,
				Scope:       f.Scope,
				Category:    f.Category,
				Path:        f.Path,
			})
		}

		data, err := yaml.Marshal(&idx)
		if err != nil {
			return fmt.Errorf("marshaling index for %s: %w", t, err)
		}

		header := "# Auto-generated by bctx. Do not edit.\n"
		indexPath := filepath.Join(bctxDir, t, "index.yaml")
		if err := os.WriteFile(indexPath, []byte(header+string(data)), 0644); err != nil {
			return fmt.Errorf("writing %s/index.yaml: %w", t, err)
		}
	}

	return nil
}

// EnsureProjectContext creates ~/.claude/bayctx/projects/<repo>/status.md with a
// template if the file doesn't already exist.
func EnsureProjectContext(repoName string) {
	if repoName == "" {
		return
	}
	projectDir := filepath.Join(config.ProjectsDir(), repoName)
	os.MkdirAll(projectDir, 0755)

	statusPath := filepath.Join(projectDir, "status.md")
	if _, err := os.Stat(statusPath); err == nil {
		return
	}

	template := fmt.Sprintf(`# %s — Project Status

## What's Built

(Describe the current state of the project here)

## Updates

### %s — initial setup
- Project context created by bctx
`, repoName, time.Now().Format("2006-01-02"))

	os.WriteFile(statusPath, []byte(template), 0644)
}

// CleanupStaleEntries removes context file entries whose paths no longer exist on disk.
func CleanupStaleEntries() (int, error) {
	files, err := List()
	if err != nil {
		return 0, fmt.Errorf("listing context files: %w", err)
	}

	cleaned := 0
	for _, f := range files {
		if _, err := os.Stat(f.Path); os.IsNotExist(err) {
			if err := Remove(f.Name); err == nil {
				cleaned++
			}
		}
	}
	return cleaned, nil
}
