"""Navigator generation for ~/.claude/CLAUDE.md."""

from datetime import datetime
from pathlib import Path
from typing import Dict, List
import yaml

from ..core.paths import (
    __version__,
    navigator_path,
    settings_dir,
    memory_dir,
    RESOURCE_TYPES,
)
from .manager import list_all, ContextFile


# Resource type descriptions
RESOURCE_TYPE_DESCRIPTIONS = {
    "rules": "Rules, coding standards, documentation",
    "skills": "Reusable skill definitions",
    "agents": "Agent configurations",
    "plugins": "Plugin definitions",
}


def generate_navigator() -> None:
    """Generate ~/.claude/CLAUDE.md navigator file.

    This creates the main entry point for Claude Code agents, providing
    navigation to all context resources, memory stores, and agent features.

    Raises:
        IOError: If navigator file can't be written.
    """
    nav_path = navigator_path()

    # Build navigator content
    content = _build_navigator_content()

    # Write to file
    nav_path.write_text(content, encoding="utf-8")

    # Also generate indexes for each resource type
    generate_all_indexes()


def _build_navigator_content() -> str:
    """Build the navigator content.

    Returns:
        Navigator markdown content.
    """
    lines = []

    # Header
    lines.append("# Claude Code Context - Bay Agent Harness\n")
    lines.append(f"*Auto-generated by bctx v{__version__} on {datetime.now().isoformat()}*\n")

    # Global rules
    lines.append("## Global Rules\n")
    lines.append("1. **Memory-First**: Check `~/.claude/memory/bay/` before assuming")
    lines.append("2. **Observation**: All actions logged automatically")
    lines.append("3. **Verification**: Pre-flight checks prevent errors")
    lines.append("4. **Index-First**: Read `index.yaml` before loading files\n")

    # Navigation table
    lines.append("## Navigation\n")
    lines.append("| Path | Description |")
    lines.append("|------|-------------|")
    lines.append("| `~/.claude/memory/bay/` | Bay agent patterns & learnings |")
    lines.append("| `~/.claude/settings/bay/` | Bay configs (read-only) |")
    lines.append("| `~/.claude/settings/bay/rules/` | Agent rules (delegation, personality, pr-quality) |")

    # Check if memory store exists and has index
    memory_index_path = memory_dir() / "index.yaml"
    if memory_index_path.exists():
        lines.append("| `~/.claude/memory/bay/index.yaml` | Memory entry catalog (READ FIRST) |")

    lines.append("")

    # Memory system section
    lines.append("## Memory System\n")
    lines.append("**Bay Memory Store**: `~/.claude/memory/bay/`\n")
    lines.append("- Read `index.yaml` FIRST (entry summaries)")
    lines.append("- Load entries on demand")
    lines.append("- Verify recalled info (memory = hint, check reality)\n")

    # Resource directories
    lines.append("## Resource Directories\n")
    lines.append("| Directory | Type | Description |")
    lines.append("|-----------|------|-------------|")

    for resource_type in RESOURCE_TYPES:
        desc = RESOURCE_TYPE_DESCRIPTIONS.get(resource_type, "")
        type_dir = settings_dir() / resource_type
        lines.append(f"| `{type_dir}/` | {resource_type} | {desc} |")

    lines.append("")
    lines.append("Read the `index.yaml` in a directory to see available resources.")
    lines.append("Manage with: `bctx files|add|rm|toggle`\n")

    # Verification rules
    lines.append("## Verification Rules\n")
    lines.append("Pre-action checks (automatically enforced):\n")
    lines.append("- **Before Edit**: Always Read file first")
    lines.append("- **Before Bash mkdir**: Verify parent directory exists")
    lines.append("- **Before git push**: Check gh auth status\n")

    # Agent features
    lines.append("## Agent Harness Features\n")
    lines.append("### Memory (Phase 2)")
    lines.append("- **Short-term memory (STM)**: Session-scoped, in-memory")
    lines.append("- **Long-term memory (LTM)**: Persistent, indexed patterns")
    lines.append("- **Episodic memory**: Historical archive\n")

    lines.append("### Observation (Phase 3)")
    lines.append("- Automatic action logging")
    lines.append("- Pattern detection (sequences, frequencies, anti-patterns)")
    lines.append("- Learning from failures\n")

    lines.append("### Verification (Phase 4)")
    lines.append("- Pre-action checks prevent errors")
    lines.append("- Configurable severity (block/warn)")
    lines.append("- User overrides available\n")

    lines.append("### Reflection (Phase 5)")
    lines.append("- Triggered on task completion, errors, user correction")
    lines.append("- Generates insights and learnings")
    lines.append("- Stores to LTM for future use\n")

    lines.append("### Multi-Agent Coordination (Phase 6)")
    lines.append("- Executor, Observer, Coordinator agents")
    lines.append("- Message-based communication")
    lines.append("- Coordination patterns (master-worker, pipeline, peer-to-peer)\n")

    # Commands
    lines.append("## Commands\n")
    lines.append("```bash")
    lines.append("# Context management")
    lines.append("bctx files              # List registered files")
    lines.append("bctx add <name> <path>  # Register context file")
    lines.append("bctx rm <name>          # Remove context file")
    lines.append("bctx toggle <name>      # Enable/disable file")
    lines.append("bctx sync               # Regenerate navigator + indexes")
    lines.append("")
    lines.append("# Agent operations")
    lines.append("bctx observe [event]    # Trigger observation")
    lines.append("bctx reflect            # Trigger reflection")
    lines.append("bctx memory <cmd>       # Memory operations")
    lines.append("bctx validate           # Validate schemas")
    lines.append("```\n")

    # Footer
    lines.append("---")
    lines.append(f"*Generated by bctx {__version__}*")

    return "\n".join(lines)


def generate_all_indexes() -> None:
    """Generate index.yaml for each resource type directory.

    Creates an index file listing all enabled context files of each type.

    Raises:
        IOError: If index files can't be written.
        yaml.YAMLError: If YAML serialization fails.
    """
    # Get all enabled context files
    files = list_all()

    # Group by type
    grouped: Dict[str, List[ContextFile]] = {t: [] for t in RESOURCE_TYPES}

    for f in files:
        if not f.enabled:
            continue

        file_type = f.type or "rules"
        if file_type in grouped:
            grouped[file_type].append(f)

    # Generate index for each type
    for resource_type in RESOURCE_TYPES:
        type_dir = settings_dir() / resource_type
        type_dir.mkdir(parents=True, exist_ok=True)

        # Build index data
        index_data = {
            "type": resource_type,
            "resources": [
                {
                    "name": f.name,
                    "description": f.description,
                    "scope": f.scope,
                    "category": f.category,
                    "path": f.path,
                }
                for f in grouped[resource_type]
            ],
        }

        # Write index.yaml
        index_path = type_dir / "index.yaml"
        header = "# Auto-generated by bctx. Do not edit.\n"

        with open(index_path, "w", encoding="utf-8") as f:
            f.write(header)
            yaml.dump(index_data, f, default_flow_style=False, sort_keys=False)
